-- Query: qPkg_Sales_Employee_Studio2
TRANSFORM Sum(qPkg_Sales_Employee_Studio1.Count) AS SumOfCount
SELECT qPkg_Sales_Employee_Studio1.Studio, qPkg_Sales_Employee_Studio1.UserID
FROM qPkg_Sales_Employee_Studio1
GROUP BY qPkg_Sales_Employee_Studio1.Studio, qPkg_Sales_Employee_Studio1.UserID
PIVOT qPkg_Sales_Employee_Studio1.PkgType;

